#+TITLE:使用TaskJuggler进行项目管理

* 引子

  在进行软件开发的过程中，使用恰当的项目管理工具可以对软件开发的整体工作进度实现更好的掌控。在项目管理工具中，微软的MS Project可以说是占据了绝大多数项目经理的桌面。但微软昂贵的授权费用，也把不少项目经理挡在了门外。好在，在开源的世界中，还有不计其数的工具可以实现项目管理的功能。TaskJuggler就是其中之一。

* TaskJuggler的特点

  作为一个项目管理工具，TaskJuggler最大的特点在于文档使用了 *纯文本* 的方式来编制。也意味这可以使用自己最喜欢的编辑器来编写项目管理文档。同时也意味当若干年后，需要重新查看这些文档的时候，不需要安装任何专用工具，使用一个文本编辑工具就可以轻松的打开文件，查看当年的工作情况记录了。这对于不断积累相关管理的经验、维护一个常年累月不断演进的系统项目来说是非常重要的。同时TaskJuggler将文档输出为MS Project文件格式等业务特性也意味着，在获得项目管理工具的便利的同时，可以不用被绑定在某一个具体的项目管理工具之上。

  作为一个完整的项目管理工具，TaskJuggler提供了任务管理、时间管理、成本管理等大量功能。并且由于使用了文本文件的方式存储信息，项目管理文档可以被集成（引用）到上级项目管理计划之中。这对于实现项目计划的逐层分解和细化提供了巨大的方便。

  与大多数项目管理工具不同，TaskJuggler本身没有图形界面——它是一个纯命令行的应用。在使用TaskJuggler时，将主要以文本编辑器编写文档，以命令行进行文档处理，以Web浏览器进行日常进度监控和报告。由于TaskJuggler是使用Ruby进行开发的，因此可以方便的运行在绝大多数操作系统之上。所以，使用TaskJuggler的对于工具的要求是非常低——现在哪个操作系统上没有文本编辑器、命令行和Web浏览器呢？

** TaskJuggler的功能特性

   TaskJuggler可以实现诸多项目管理功能，可以说TaskJuggler是一个超越了甘特图绘制功能的项目管理工具。

   在它的 [[http://www.taskjuggler.org/][主页]] 上，能够看到TaskJuggler的基本功能特性：

   * 基本属性
     + 管理项目相关的任务、资源和财务收支
     + 强大的待办管理功能
     + 详细的参考手册
     + 简单的安装
     + 多平台运行，可于Linux、Unix、Windows、MacOS等操作系统
     + 与VIM等编辑器的全面集成功能
   * 高级日程管理
     + 自动化的资源分配和任务冲突解决功能
     + 针对项目可做无限数量的场景（基线）分析
     + 灵活的工作时间和休假管理
     + 支持工作排班（shift working）
     + 多时区支持
   * 财务管理
     + 支持任务的启动成本和结束成本属性
     + 可基于成本分配资源使用量
     + 基于成本模型的任务/资源管理
     + 支持成本/利润分析
   * 报告功能
     + 详细而灵活的报表功能，便于在需要的时候查找所需信息
     + 强大的信息过滤功能，支持为特定对象提供项目细节信息
     + 支持项目执行计划和状态报告
   * 扩展性及企业功能
     + 向上级项目的集成功能
     + 支持中央资源分配数据库
     + 管理角色和复杂的汇报线条
     + 支持宏的项目描述语言
     + 对多核或多CPU系统的支持
     + 支持项目管理团队和版本管理系统
     + 支持输出到 Microsoft Project 和 Computer Associates Clarity
   * Web发布和协作功能
     + 可发布为HTML格式的项目报告
     + 支持CSV格式数据导出，便于和办公软件交互数据
     + 支持iCalendar格式的数据导出，便于与各类日历及效率软件交互
     + 内置Web服务器功能，实现交互式项目报告访问功能
     + 基于服务器的时间表系统，支持项目进度及实际工作进度报告。

* TaskJuggler运行环境说明

  TaskJuggler使用Ruby开发，因此TaskJuggler理论上可以在任何具有Ruby运行环境的平台上使用。此外，TaskJuggler确实存在一些对运行环境的依赖关系，在使用TaskJuggler前需要确认系统要求
  
** 关于操作系统的说明

   * Linux           ：TaskJuggler的主要开发平台。TaskJuggler在OpenSUSE近期版本中测试通过。
   * 其他Unix操作系统：应该可以运行，但没有在这些系统上进行测试
   * Windows         ：Window7及其以前的版本应该可以运行，但由于缺少相应的维护人员，TaskJuggler没有在这些操作系统上进行测试
   * MacOSX          ：应该可以运行，但没有进行测试。更老的MacOS版本可能无法运行。

** 其他需要的软件

   * Ruby
     TaskJuggler使用Ruby进行开发，因此需要Ruby运行环境才可以使用TaskJuggler。绝大多数Linux发行版和MacOSX Leopard中都已经提供了Ruby运行环境。对于Windows用户来说，有一键安装的Ruby运行环境。建议使用Ruby2.0版本。Ruby1.9.1版本在多核系统上存在一些Bug。如果需要使用非ASCII字符集的，需要使用1.9.2及更新的Ruby发行版本。
   * RubyGem
     RubyGem是Ruby下的包管理工具，可以按安装TaskJuggler时自动完成相关依赖包的安装功能。
     
* TaskJuggler的安装

  TaskJuggler的安装非常简单，在Ubuntu14.04上，我的安装过程如下：

  1. 安装Ruby2.0运行环境

     #+BEGIN_SRC sh
       sudo apt-get install ruby2.0
     #+END_SRC

  2. 安装TaskJuggler

     #+BEGIN_SRC sh
       sudo gem install taskjuggler
     #+END_SRC

* 生成项目实施报告

* 小结
